Move name to orange_livebox, incremental data updates
cozy/cozy-konnector-orangevod pull request #2
Opened 2017-05-29 15:47 UTC by jacquarg

* Move name to Orange livebox (Orange request)
* add permission for doctype org.fing.mesinfos.videostream
* ues modified base_konnector, to allow persistence of some usefull values. In that case, lastVideoStreal timestamp, to perform incremental update on each run.
* add env.js file

* ? should we remove permission for doctype files ?

2017-05-29 15:50 UTC, jacquarg commented
Ping @doubleface  ; )

2017-05-29 16:39 UTC, doubleface approved these changes
It looks all good to me. It would be better to find a way to inherit the base konnector instead of replacing it but I don't see it at the moment.

2017-05-29 16:44 UTC, doubleface commented
@jacquarg The files permission is still needed since you enhanced base konnector still still checks that the folderPath in cozyFields exists. If your remove that part, the files permission in not needed anymore.

2017-05-30 13:35 UTC, jacquarg commented
@doubleface 
I just add a test to make the files permission optional.

I didn't try to enhance base_konnector, as I expected to just upgrade it in konnector-libb with this version ; )

2017-05-30 13:42 UTC, doubleface requested changes

2017-05-30 13:42 UTC, doubleface commented on base_konnector_with_remember.js
> +            console.log(JSON.stringify(cozyFields))
There is still a console.log that I don't think you want to keep

2017-05-30 13:43 UTC, doubleface approved these changes

2017-05-30 13:43 UTC, doubleface commented
@jacquarg then it is ok for me

2017-05-30 13:44 UTC, doubleface commented
I will merge it when you remove the console.log

2017-05-30 13:45 UTC, jacquarg commented
Just did  : )

2017-05-30 13:49 UTC, merged

2017-05-30 13:50 UTC, jacquarg commented
Thanks